# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
  displayName: 'Restore Nuget Packages'

- task: DotNetCoreCLI@2
  displayName: "Build project - .Net Core 5.0.x"
  inputs:
    command: 'build'
    arguments: '--no-restore'
    projects: 'src/Base.API/Base.API.csproj'
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
      
      dir

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'src/Base.Test.Unit/Base.Test.Unit.csproj'
    arguments: '--no-restore'
  displayName: 'Run Tests'

- task: DotNetCoreCLI@2
  displayName: 'Publish dotnet Api'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/Base.API/Base.API.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore -o $(Build.ArtifactStagingDirectory)/Output'
    modifyOutputPath: false

- task: CmdLine@2
  inputs:
    script: |
      echo Workin on: $(Build.ArtifactStagingDirectory)/Output
      dir
    workingDirectory: $(Build.ArtifactStagingDirectory)/Output


